version: '3'
services:
  mysql:
    container_name: quepid_db
    image: mysql:5.6.37
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password

  redis:
    container_name: quepid_redis
    image: redis:6.0.5
    ports:
      - 6379:6379

  app:
    container_name: quepid_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - LAUNCHY_DRY_RUN=true # dev only letter_opener gem wants to open a browser
      - BROWSER=/dev/null
    volumes:
      - .:/srv/app
      - ./log:/log
    ports:
      - 3000:3000
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
